name: Check PRs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Perform static analysis checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Prepare Node environment
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run Prettier
        run: npx prettier --check .
      - name: Run ESLint on web client
        run: cd web && yarn lint
      - name: Run Typescript checker on web client
        run: tsc --pretty --project web/tsconfig.json --noEmit
      - name: Run Typescript checker on cloud functions
        run: tsc --pretty --project functions/tsconfig.json --noEmit
